export const SimpleIcons = {
  Eye: () => <span className="text-sm">👁</span>,
  EyeOff: () => <span className="text-sm">🙈</span>,
  Mail: () => <span className="text-sm">✉</span>,
  Lock: () => <span className="text-sm">🔒</span>,
  User: () => <span className="text-sm">👤</span>,
  Plus: () => <span className="text-lg font-bold">+</span>,
  X: () => <span className="text-lg font-bold">×</span>,
  Check: () => <span className="text-sm">✓</span>,
  ChevronDown: () => <span className="text-sm">▼</span>,
  ChevronRight: () => <span className="text-sm">▶</span>,
  ChevronLeft: () => <span className="text-sm">◀</span>,
  ChevronUp: () => <span className="text-sm">▲</span>,
  Search: () => <span className="text-sm">🔍</span>,
  Menu: () => <span className="text-sm">☰</span>,
  MoreHorizontal: () => <span className="text-sm">⋯</span>,
  Edit: () => <span className="text-sm">✏</span>,
  Trash: () => <span className="text-sm">🗑</span>,
  Download: () => <span className="text-sm">⬇</span>,
  Save: () => <span className="text-sm">💾</span>,
  ArrowLeft: () => <span className="text-sm">←</span>,
  ArrowRight: () => <span className="text-sm">→</span>,
  FileText: () => <span className="text-sm">📄</span>,
  Briefcase: () => <span className="text-sm">💼</span>,
  GraduationCap: () => <span className="text-sm">🎓</span>,
  Code: () => <span className="text-sm">💻</span>,
  Settings: () => <span className="text-sm">⚙</span>,
  HelpCircle: () => <span className="text-sm">❓</span>,
  LayoutDashboard: () => <span className="text-sm">📊</span>,
  Phone: () => <span className="text-sm">📞</span>,
  MapPin: () => <span className="text-sm">📍</span>,
  Globe: () => <span className="text-sm">🌐</span>,
  Linkedin: () => <span className="text-sm">💼</span>,
  Copy: () => <span className="text-sm">📋</span>,
  Calendar: () => <span className="text-sm">📅</span>,
  Loader: () => <span className="animate-spin text-sm">⟳</span>,
  Camera: () => <span className="text-sm">📷</span>,
  LogOut: () => <span className="text-sm">🚪</span>,
  Filter: () => <span className="text-sm">🔽</span>,
  Circle: () => <span className="text-xs">●</span>,
  Minus: () => <span className="text-sm">−</span>,
  Grip: () => <span className="text-sm">⋮⋮</span>,
  Zap: () => <span className="text-sm">⚡</span>,
  Palette: () => <span className="text-sm">🎨</span>,
  BarChart: () => <span className="text-sm">📊</span>,
  Shield: () => <span className="text-sm">🛡</span>,
  Users: () => <span className="text-sm">👥</span>,
}
